# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa2dbf84836e80826435baa7b61c9143ce451c4657a85537a40ab95c20e626a39c6242ff0c8ee51a39b874ad20b6bb904a6b314fd327c99f4c7e1f16d9dc5290

test:
  secret_key_base: 686f0e0728a97d7ec2e166928952a2a0488a3d8793c465b238dec5c3b08bd1b279dbb4602b74fc257fcb8455ca7899ac34ae410aee1b1bdff5ebfb21341a702a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
